baseurl = "https://sergiosjs.github.io/"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "<script async src='https://www.googletagmanager.com/gtag/js?id=UA-159475896-1'></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'UA-159475896-1');</script>"

	email = "sergio7sjs@gmail.com"

    urlprofilepic = "https://avatars2.githubusercontent.com/u/2502244"
	
	title = "Sérgio José de Sousa"
	subtitle = "Portfólio"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/sergiosjs"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/sergiosjs"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com/in/sergiosjs/"

	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"
